# Generated by Django 6.0.6 on 2026-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_delivery_timeline',
            field=models.CharField(blank=True, help_text='e.g., Today by 6 PM', max_length=100, null=True),
        ),
    ]
