# Generated by Django 6.0.6 on 2026-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointmentslot_service_alter_user_managers_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('client_email', models.EmailField(max_length=254)),
                ('service_name', models.CharField(max_length=100)),
                ('action_by', models.CharField(help_text='Email of the user/staff who triggered this action', max_length=255)),
                ('status_changed_to', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
