name: Sync to Renation

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Code to Renation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Explicitly pass token in the URL mapping
          git remote add destination https://${{ secrets.SYNC_TOKEN }}@github.com/rajamii/renation.git
          
          git push destination main --force